export const dummyData = 
    {
        data: [
          {
            "ID": "1",
            "Comercio": "Almacen SRL",
            "CUIT": "2836654211",
            "Concepto 1": '',
            "Concepto 2": '',
            "Concepto 3": '',
            "Concepto 4": '',
            "Concepto 5": '',
            "Concepto 6": '',
            "Balance actual": `65100`,
            "Activo": 0,
            "Ultima venta": "31/04/2021"
          },
          {
            "ID": "2",
            "Comercio": "Verduleria SRL",
            "CUIT": "2595857141",
            "Concepto 1": '',
            "Concepto 2": '',
            "Concepto 3": '',
            "Concepto 4": '',
            "Concepto 5": '',
            "Concepto 6": '',
            "Balance actual": `91300`,
            "Activo": 0,
            "Ultima venta": "01/04/2021"
          },
          {
            "ID": "3",
            "Comercio": "Carniceria SRL",
            "CUIT": "2375621230",
            "Concepto 1": '',
            "Concepto 2": '',
            "Concepto 3": '',
            "Concepto 4": '',
            "Concepto 5": '',
            "Concepto 6": '',
            "Balance actual": `921121`,
            "Activo": 0,
            "Ultima venta": "09/03/2021"
          },
          {
            "ID": "4",
            "Comercio": "Taller Mecanico SRL",
            "CUIT": "2523526986",
            "Concepto 1": '',
            "Concepto 2": '',
            "Concepto 3": '',
            "Concepto 4": '',
            "Concepto 5": '',
            "Concepto 6": '',
            "Balance actual": `25802`,
            "Activo": true,
            "Ultima venta": "18/06/2021"
          },
          {
            "ID": "5",
            "Comercio": "Peluqeria SRL",
            "CUIT": "2823526982",
            "Concepto 1": '',
            "Concepto 2": '',
            "Concepto 3": '',
            "Concepto 4": '',
            "Concepto 5": '',
            "Concepto 6": '',
            "Balance actual": `113111`,
            "Activo": true,
            "Ultima venta": "18/06/2021"
          },
          {
            "ID": "6",
            "Comercio": "Panaderia SRL",
            "CUIT": "2932352698",
            "Concepto 1": '',
            "Concepto 2": '',
            "Concepto 3": '',
            "Concepto 4": '',
            "Concepto 5": '',
            "Concepto 6": '',
            "Balance actual": `92280`,
            "Activo": true,
            "Ultima venta": "18/06/2021"
          },
          {
            "ID": "7",
            "Comercio": "Pedicuria SRL",
            "CUIT": "2963526854",
            "Concepto 1": '',
            "Concepto 2": '',
            "Concepto 3": '',
            "Concepto 4": '',
            "Concepto 5": '',
            "Concepto 6": '',
            "Balance actual": `550985`,
            "Activo": true,
            "Ultima venta": "18/06/2021"
          },
          {
            "ID": "8",
            "Comercio": "Clinica SRL",
            "CUIT": "2033625441",
            "Concepto 1": '',
            "Concepto 2": '',
            "Concepto 3": '',
            "Concepto 4": '',
            "Concepto 5": '',
            "Concepto 6": '',
            "Balance actual": `160668`,
            "Activo": true,
            "Ultima venta": "18/06/2021"
          },
          {
            "ID": "9",
            "Comercio": "Veterinaria SRL",
            "CUIT": "2036873619",
            "Concepto 1": '',
            "Concepto 2": '',
            "Concepto 3": '',
            "Concepto 4": '',
            "Concepto 5": '',
            "Concepto 6": '',
            "Balance actual": `150222`,
            "Activo": true,
            "Ultima venta": "18/06/2021"
          },
          {
            "ID": "10",
            "Comercio": "Jugueteria SRL",
            "CUIT": "2698714024",
            "Concepto 1": '',
            "Concepto 2": '',
            "Concepto 3": '',
            "Concepto 4": '',
            "Concepto 5": '',
            "Concepto 6": '',
            "Balance actual": `68200`,
            "Activo": true,
            "Ultima venta": "18/06/2021"
          },
          {
            "ID": "11",
            "Comercio": "Santeria SRL",
            "CUIT": "2754125326",
            "Concepto 1": '',
            "Concepto 2": '',
            "Concepto 3": '',
            "Concepto 4": '',
            "Concepto 5": '',
            "Concepto 6": '',
            "Balance actual": `80000`,
            "Activo": true,
            "Ultima venta": "18/06/2021"
          },
          {
            "ID": "12",
            "Comercio": "Rotiseria SRL",
            "CUIT": "2698765292",
            "Concepto 1": '',
            "Concepto 2": '',
            "Concepto 3": '',
            "Concepto 4": '',
            "Concepto 5": '',
            "Concepto 6": '',
            "Balance actual": `35520`,
            "Activo": true,
            "Ultima venta": "18/06/2021"
          },
        ],
        page: 1,
        pages: 100,
        rowsTotal: 10,
        rowsPerPage: 4,
}